### ISSUE TITLE
Can't load the plugin on Folia

### ISSUE THREAD

**Issue by qbasty** [MajekDev/HexNicks#120]
**Describe the bug**
```
[12:27:41 ERROR]: [DirectoryProviderSource] Error loading plugin: File 'plugins/hexnicks-3.1.1.jar' failed to load!
java.lang.RuntimeException: File 'plugins/hexnicks-3.1.1.jar' failed to load!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[kaiiju-1.19.4.jar:git-Kaiiju-"f8a95fc"]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$2(DirectoryProviderSource.java:32) ~[kaiiju-1.19.4.jar:git-Kaiiju-"f8a95fc"]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
        at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:30) ~[kaiiju-1.19.4.jar:git-Kaiiju-"f8a95fc"]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[kaiiju-1.19.4.jar:git-Kaiiju-"f8a95fc"]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[kaiiju-1.19.4.jar:git-Kaiiju-"f8a95fc"]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[kaiiju-1.19.4.jar:git-Kaiiju-"f8a95fc"]
        at net.minecraft.server.Main.main(Main.java:126) ~[kaiiju-1.19.4.jar:git-Kaiiju-"f8a95fc"]
        at org.bukkit.craftbukkit.Main.main(Main.java:322) ~[kaiiju-1.19.4.jar:git-Kaiiju-"f8a95fc"]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.RuntimeException: Could not load plugin 'HexNicks v3.1.1' as it is not marked as supporting Folia!
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[kaiiju-1.19.4.jar:git-Kaiiju-"f8a95fc"]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[kaiiju-1.19.4.jar:git-Kaiiju-"f8a95fc"]
        at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:67) ~[kaiiju-1.19.4.jar:git-Kaiiju-"f8a95fc"]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[kaiiju-1.19.4.jar:git-Kaiiju-"f8a95fc"]
        ... 20 more
```

**To Reproduce**
I installed the latest version and restarted the server.

**Software (please complete the following information):**
 - Latest plugin on https://github.com/KaiijuMC/Kaiiju

**Additional context**

**Comment by xGinko** [comment]
![weird, plugin yml seems to have the marker](https://github.com/MajekDev/HexNicks/assets/83339096/a3006fa9-1c91-4736-a0c8-3245504d3288)

**Comment by xiaoluofa** [comment]
> weird, plugin yml seems to have the marker
> 
> ![weird, plugin yml seems to have the marker](https://private-user-images.githubusercontent.com/83339096/274224851-a3006fa9-1c91-4736-a0c8-3245504d3288.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjAwMDQsIm5iZiI6MTcxMDI1OTcwNCwicGF0aCI6Ii84MzMzOTA5Ni8yNzQyMjQ4NTEtYTMwMDZmYTktMWM5MS00NzM2LWEwYzgtMzI0NTUwNGQzMjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE2MDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZGY4NGJlODU3ZGEwOGZkY2MxOGM4YzEwZmJmOTFlNGU2MDFkYzc3N2Y1MDhjYmJhNDQzYmIxNTYyMmE0Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6NsZ5CHPJi_RU7R3OuEZmHBDRzbmZGeGVlRCFFSSkhk)

cant using mysql in folia
