### ISSUE TITLE
Plugin breaking on 1.18 purpur snapshots

### ISSUE THREAD

**Issue by c1oneman** [MajekDev/HexNicks#41]
**Describe the bug**
Looking like the plugin can not boot due to something is null that shouldn't be?

**To Reproduce**
1. Install HexNicks on a purpur server on purpur 1.18 (purepur-1.18-1431)
2. Run server
3. See error

**Screenshots**

**Software (please complete the following information):**
 - Server Implementation: [Purpur]
 - Minecraft Version [NA]
 - Java Version [17]
 - Plugin Version [2.2.0]

**Additional context**
ERROR on loading plugin (disabled)
`[20:07:08] [Server thread/INFO]: [HexNicks] Enabling HexNicks v2.2.0
[20:07:08] [Server thread/INFO]: [HexNicks] Running on PaperMC server software.
[20:07:08] [Server thread/INFO]: [HexNicks] Successfully loaded nicknames from Json storage.
[20:07:08] [Server thread/ERROR]: Error occurred while enabling HexNicks v2.2.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.get(String, Object)" because "section" is null
	at org.bukkit.configuration.MemorySection.get(MemorySection.java:265) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.MemorySection.get(MemorySection.java:230) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.MemorySection.contains(MemorySection.java:119) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.MemorySection.contains(MemorySection.java:114) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at dev.majek.relocations.com.tchristofferson.configupdater.KeyBuilder.parseLine(KeyBuilder.java:29) ~[HexNicks-2.2.0.jar:?]
	at dev.majek.relocations.com.tchristofferson.configupdater.ConfigUpdater.parseIgnoredSections(ConfigUpdater.java:156) ~[HexNicks-2.2.0.jar:?]
	at dev.majek.relocations.com.tchristofferson.configupdater.ConfigUpdater.update(ConfigUpdater.java:29) ~[HexNicks-2.2.0.jar:?]
	at dev.majek.hexnicks.Nicks.reload(Nicks.java:328) ~[HexNicks-2.2.0.jar:?]
	at dev.majek.hexnicks.Nicks.onEnable(Nicks.java:156) ~[HexNicks-2.2.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[purpur-1.18.jar:git-Purpur-1431]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[purpur-1.18.jar:git-Purpur-1431]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:730) ~[purpur-1.18.jar:git-Purpur-1431]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:506) ~[purpur-1.18.jar:git-Purpur-1431]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:347) ~[purpur-1.18.jar:git-Purpur-1431]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[purpur-1.18.jar:git-Purpur-1431]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.jar:git-Purpur-1431]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:07:08] [Server thread/INFO]: [HexNicks] Disabling HexNicks v2.2.0`

**Comment by Majekdor** [comment]
I'm told this is fixed in the latest Purpur build. Will re-open if it's not.
